# common column names
MTM_X_COL = "MTM8_X"
MTM_Y_COL = "MTM8_Y"
LONG_COL = "LONGITUDE"
LAT_COL = "LATITUDE"

# incidents dataset
INC_ID_COL = "INCIDENT_NBR"
INC_DATE_COL = "CREATION_DATE_TIME"
INC_TYPE_COL = "INCIDENT_TYPE_DESC"
INC_GROUP_DESCRIPTION_COL = "DESCRIPTION_GROUPE"
INC_FF_STATION_COL = "CASERNE"
INC_MUN_COL = "NOM_VILLE"
INC_ARR_COL = "NOM_ARROND"
INC_DIVISION_COL = "DIVISION"
INC_NB_UN_COL = "NOMBRE_UNITES"

# firefighter stations dataset
FF_CASERNE_COL = "CASERNE"
FF_NBCIV_COL = "NO_CIVIQUE"
FF_RUE_COL = "RUE"
FF_ARR_COL = "ARRONDISSEMENT"
FF_MUN_COL = "VILLE"
FF_DTSTART_COL = "DATE_DEBUT"
FF_DTEND_COL = "DATE_FIN"

# new columns
BOROUGH_COL = "BOROUGH"
