from enum import Enum


class ExternalDatabases(Enum):
    ACTES_CRIMINELS = "actes_criminels"
    CENSUS_2021 = "census_2021"
    FIRE_STATIONS = "fire_stations"
    INTERVENTIONS_SIM = "interventions_sim"
    LIM_ADMIN_MTL = "limites_administratives_agglomeration"
    PROPERTY_ASSESSMENT = "unites_evaluation_fonciere"
    TAX_ROLLS = "taxes_municipales"
    TAX_ROLL_AHUNTSIC = "taxes_municipales_Ahuntsic"
    TAX_ROLL_ANJOU = "taxes_municipales_Anjou"
    TAX_ROLL_COTE_DES_NEIGES = "taxes_municipales_CoteDesNeiges"
    TAX_ROLL_ILE_BIZARD = "taxes_municipales_IleBizardSainteGenevieve"
    TAX_ROLL_LACHINE = "taxes_municipales_LaChine"
    TAX_ROLL_LASALLE = "taxes_municipales_LaSalle"
    TAX_ROLL_PLATEAU = "taxes_municipales_LePlateauMontRoyal"
    TAX_ROLL_SUD_OUEST = "taxes_municipales_LeSudOuest"
    TAX_ROLL_HOCHELAGA = "taxes_municipales_MercierHochelagaMaisonneuve"
    TAX_ROLL_MTL_NORD = "taxes_municipales_MontrealNord"
    TAX_ROLL_OUTREMONT = "taxes_municipales_Outremont"
    TAX_ROLL_PIERREFONDS = "taxes_municipales_PierrefondsRoxboro"
    TAX_ROLL_RIV_DES_PRAIRIES = "taxes_municipales_RiviereDesPrairies"
    TAX_ROLL_ROSEMONT = "taxes_municipales_RosemontLaPetitePatrie"
    TAX_ROLL_ST_LAURENT = "taxes_municipales_SaintLaurent"
    TAX_ROLL_ST_LEONARD = "taxes_municipales_SaintLeonard"
    TAX_ROLL_VERDUN = "taxes_municipales_Verdun"
    TAX_ROLL_VILLEMARIE = "taxes_municipales_VilleMarie"
    TAX_ROLL_VILLERAY = "taxes_municipales_VilleraySaintMichelParcExtension"
